baseURL = "https://www.z3r0d4y.com/"
languageCode = "en-us"
title = "RAZMJOO'S PERSONAL WEBSITE - CYBER SECUIRTY ENGINEER"
theme = "hugo.386"
preserveTaxonomyNames = true

[markup.goldmark.renderer]
unsafe= true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Blog(ish)"

    # # The subtitle to display under the title in the home page
    # mainpagesubtitle = "CYBER SECURITY ENGINEER + CARPE DIEM = <blink><a>HACKER</a></blink>"
    # injectted to /themes/hugo.386/layouts/index.html,404.html directly instead

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Roses are red, violets are blue, this blog is useless and I don't have a clue! My world is just ones and zeros, and its population is full of hacker heroes!"

    # The name to display in the copyright section in the footer
    copyrightname = "Raz"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://www.z3r0d4y.com"

    # Show the "built on Hugo" disclaimer
    # showhugo = true

    # Urls for social networks
    # facebook = "https://facebook.com"
    twitter = "https://twitter.com/razilowfsky"
    linkedin = "https://www.linkedin.com/in/razmjoo/"
    github = "https://github.com/Ali-Razmjoo"
    # gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

    # Meta description
    # description in markdown file will be used as meta description in each page/post
    description = "RAZMJOO'S PERSONAL WEBSITE - CYBER SECUIRTY ENGINEER" # used in themes/hugo.386/layouts/partials/head.html

[params.copyright]
    name = "Raz"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://www.z3r0d4y.com"

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "This website is `lynx` friendly"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 1

  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 2          # A number to order the buttons in the navbar


  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "mailto:r@z3r0d4y.com"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

