name: Deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building ...'
      run: |
        ls
        docker run --rm -it -v $(pwd):/src klakegg/hugo --help