name: Deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Building ...'
      run: |
        ls -lah
        