name: Deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Building ...'
      run: |
        mkdir -p ../public
        docker run --rm  -v $(pwd):/src klakegg/hugo:0.74.3 -d ../public
        git checkout gh-pages
        cp -r ../public/* .
        git commit -a -m "update blog"
        git push -f
        